# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shopping_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 472)
        MainWindow.setStyleSheet("color")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(31, 41, 128, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:white; color:red;")
        self.label.setObjectName("label")
        self.checkBox_puri = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_puri.setGeometry(QtCore.QRect(30, 120, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.checkBox_puri.setFont(font)
        self.checkBox_puri.setObjectName("checkBox_puri")
        self.checkBox_kvercxi = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_kvercxi.setGeometry(QtCore.QRect(30, 180, 87, 20))
        self.checkBox_kvercxi.setObjectName("checkBox_kvercxi")
        self.checkBox_yveli = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_yveli.setGeometry(QtCore.QRect(30, 150, 87, 20))
        self.checkBox_yveli.setObjectName("checkBox_yveli")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 310, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.checkBox_arajani = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_arajani.setGeometry(QtCore.QRect(30, 210, 87, 20))
        self.checkBox_arajani.setObjectName("checkBox_arajani")
        self.checkBox_brinji = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_brinji.setGeometry(QtCore.QRect(30, 240, 87, 20))
        self.checkBox_brinji.setObjectName("checkBox_brinji")
        self.checkBox_pomidori = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_pomidori.setGeometry(QtCore.QRect(30, 270, 101, 21))
        self.checkBox_pomidori.setObjectName("checkBox_pomidori")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 90, 104, 26))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(180, 120, 201, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result.sizePolicy().hasHeightForWidth())
        self.label_result.setSizePolicy(sizePolicy)
        self.label_result.setText("")
        self.label_result.setWordWrap(True)
        self.label_result.setObjectName("label_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "საყიდლების სია"))
        self.checkBox_puri.setText(_translate("MainWindow", "პური"))
        self.checkBox_kvercxi.setText(_translate("MainWindow", "კვერცხი"))
        self.checkBox_yveli.setText(_translate("MainWindow", "ყველი"))
        self.pushButton.setText(_translate("MainWindow", "მზადაა!"))
        self.checkBox_arajani.setText(_translate("MainWindow", "არაჟანი"))
        self.checkBox_brinji.setText(_translate("MainWindow", "ბრინჯი"))
        self.checkBox_pomidori.setText(_translate("MainWindow", "პომიდორი"))
        self.comboBox.setCurrentText(_translate("MainWindow", "საუზმე"))
        self.comboBox.setItemText(0, _translate("MainWindow", "საუზმე"))
        self.comboBox.setItemText(1, _translate("MainWindow", "სადილი"))
        self.comboBox.setItemText(2, _translate("MainWindow", "ვახშამი"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())